$ docker build -t to-do-app-openjdk - < Dockerfile-openjdk
Sending build context to Docker daemon  3.072kB
Error response from daemon: Dockerfile parse error line 4: unknown instruction: &&

FROM debian:buster-slim

RUN rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get update && apt-get upgrade -y
&& apt-get install -y --no-install-recommends curl ca-certificates
&& rm -rf /var/lib/apt/lists/*

ENV JAVA_VERSION jdk-10.0.2+13

RUN set -eux;
ARCH="$(dpkg --print-architecture)";
case "${ARCH}" in
amd64|x86_64)
ESUM_URL='https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/download/jdk-10.0.2%2B13.1/OpenJDK10U-jre_x64_linux_hotspot_10.0.2_13.tar.gz.sha256.txt';
BINARY_URL='https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/download/jdk-10.0.2%2B13.1/OpenJDK10U-jre_x64_linux_hotspot_10.0.2_13.tar.gz';
;;
)
echo "Unsupported arch: ${ARCH}";
exit 1;
;;
esac;
curl -Lso /tmp/OpenJDK10U-jre_x64_linux_hotspot_10.0.2_13.tar.gz ${BINARY_URL};
curl -Lso /tmp/sha256sum.txt ${ESUM_URL};
cd /tmp;
cat /tmp/sha256sum.txt | sha256sum -c -;
mkdir -p /opt/java/openjdk;
cd /opt/java/openjdk;
tar -xf /tmp/OpenJDK10U-jre_x64_linux_hotspot_10.0.2_13.tar.gz;
## jdir=$(dirname $(dirname $(find /opt/java/openjdk -name javac)));
## mv ${jdir}/ /opt/java/openjdk;
rm -rf /tmp/OpenJDK10U-jre_x64_linux_hotspot_10.0.2_13.tar.gz /tmp/sha256sum.txt;

ENV JAVA_HOME=/opt/java/openjdk
PATH="/opt/java/openjdk/bin:$PATH"
