# Define 'Service' to expose FrontEnd Application
apiVersion: v1
kind: Service
metadata:
  name: sample-app-frontend
  labels:
    app-id: sampleapp
    app-tier: web
    tenant-id: finance
    tenant-team: dev1
spec:
  selector: # pod labels should match these
    app-id: sampleapp
    app-tier: web
    tenant-id: finance
    tenant-team: dev1
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer # use NodePort if you are not running Kubernetes on Cloud
---
# 'Deployment' to manage of configuration of frontEnd Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-frontend
  labels: # pod labels should match these
    app-id: sampleapp
    app-tier: web
    tenant-id: finance
    tenant-team: dev1
spec:
  replicas: 2  # number of replicas of frontEnd application
  selector:
    matchLabels: 
      app-id: sampleapp
      app-tier: web 
      tenant-id: finance
      tenant-team: dev1 
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app-id: sampleapp
        app-tier: web  
        tenant-id: finance
        tenant-team: dev1
    spec:                 
      containers: 
      - name: sample-app-frontend 
        image: kubernetesdemo/sample-app-frontend # docker image of frontend application
        env: # Setting Environmental Variables
          -  name: SERVER_URI # Setting Backend URI from configMap
             valueFrom:
               configMapKeyRef:
                 name: backend-conf # Name of configMap
                 key: server-uri
        ports:
        - containerPort: 8080
