kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  mysql-pv-claim
  labels:
    app:  sample-app
  annotations:
    volume.beta.kubernetes.io/storage-class: sample-app 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi
