{{- if and ( eq .Values.backend.config.type "file") (hasKey .Values.backend.config "content") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
  labels:
      app: {{ .Values.backend.name }}
      tier: {{ .Values.backend.labels.tier }}
data:
  application.yml:
    {{ toYaml .Values.backend.config.content | indent 4  }}
{{- end }}