apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- with .Values.frontend.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
    {{- with .Values.frontend.labels }}
{{ toYaml . | indent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
    {{- with .Values.frontend.labels }}
{{ toYaml . | indent 8 }}
    {{- end }}
      annotations:
        {{ toYaml .Values.frontend.podAnnotations | indent 8 }}
    spec:
      serviceAccountName: {{ template "spring.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.frontend.securityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
          - name: SERVER_URI   # Setting Backend URI from externalservice
            value: backend-alb-service
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          {{- if .Values.frontend.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.frontend.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.frontend.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.frontend.readinessProbe | indent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
    {{- with .Values.frontend.nodeSelector }}
      imagePullSecrets:
        - name: "{{ .Values.frontend.name }}-registry"
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.frontend.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.frontend.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}